export const menuItemsData = [
        {
          id: 1,
          name: 'Salad',
          price: 20,
          img: '/images/Salad.jpg',
        },
        {
          id: 2,
          name: 'Summer Asian Slaw',
          price: 40,
          img: '/images/Asian-Slaw.jpg',
        },
        {
          id: 3,
          name: 'Burger',
          price: 50,
          img: '/images/burger.jpg',
        },
        {
          id: 4,
          name: 'White sauce pasta',
          price: 100,
          img: '/images/White-Sauce-Pasta.jpg',
        },
        {
          id: 5,
          name: 'Red sauce pasta',
          price: 100,
          img: '/images/redpasta.jpeg',
        },
        {
          id: 6,
          name: 'Tuity fruity ice cream',
          price: 24,
          img: '/images/tutti-frutti-ice-cream.jpg',
        },
        {
          id: 7,
          name: 'Granola cereal bowl',
          price: 30,
          img: '/images/granola cereal.jpg',
        },
        {
          id: 8,
          name: 'Palm bowl',
          price: 60,
          img: '/images/palm mainz bowls.jpg',
        },
        {
          id: 9,
          name: 'Tigela smoothie',
          price: 80,
          img: '/images/tigela smoothie.jpg',
        },
        {
          id: 10,
          name: 'Breakfast cereal',
          price: 35,
          img: '/images/breakfast cereals.jpg',
        },
        {
          id: 11,
          name: 'Cuisine of Hawaii',
          price: 150,
          img: '/images/hawaii cuisine.jpg',
        },
        {
          id: 12,
          name: 'Fried chicken',
          price: 180,
          img: '/images/Fried-Chicken.jpg',
        },
        {
          id: 13,
          name: 'Greek salad',
          price: 40,
          img: '/images/Greek-Salad.jpg',
        },
        {
          id: 14,
          name: 'Hamburger',
          price: 70,
          img: '/images/hamburger.jpg',
        },
        {
          id: 15,
          name: 'Noodles',
          price: 60,
          img: '/images/noodles.jpg',
        },
        {
          id: 16,
          name: 'Butter chicken with naan',
          price: 250,
          img: '/images/butter chicken with naan.jpg',
        },
        {
          id: 17,
          name: 'Pizza',
          price: 180,
          img: '/images/pizza.jpg',
        },
        {
          id: 18,
          name: 'Peri Peri Fries',
          price: 70,
          img: '/images/fries.jpg',
        },
        {
          id: 19,
          name: 'Cheese Grilled Sandwich',
          price: 140,
          img: '/images/sandwich.jpg',
        },
      ];